// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5yyAD8NRyEMV12APa5UW68ARzGG27ZmI',
    appId: '1:277457472198:web:324ea94f03aa2955aea5c7',
    messagingSenderId: '277457472198',
    projectId: 'mynotes-af887',
    authDomain: 'mynotes-af887.firebaseapp.com',
    storageBucket: 'mynotes-af887.appspot.com',
    measurementId: 'G-HPN48E5K6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX6D53VFqBz4FVJbgHH-5wDHqUGVFDIVk',
    appId: '1:277457472198:android:bf7fd6ae45b28a12aea5c7',
    messagingSenderId: '277457472198',
    projectId: 'mynotes-af887',
    storageBucket: 'mynotes-af887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAitapoU3V29jpLBsJZ24L52H_FDqS8WZo',
    appId: '1:277457472198:ios:de207c3d8863e9abaea5c7',
    messagingSenderId: '277457472198',
    projectId: 'mynotes-af887',
    storageBucket: 'mynotes-af887.appspot.com',
    iosClientId: '277457472198-j3pl6ar8mgskd9vli9l9qdng3896akrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAitapoU3V29jpLBsJZ24L52H_FDqS8WZo',
    appId: '1:277457472198:ios:de207c3d8863e9abaea5c7',
    messagingSenderId: '277457472198',
    projectId: 'mynotes-af887',
    storageBucket: 'mynotes-af887.appspot.com',
    iosClientId: '277457472198-j3pl6ar8mgskd9vli9l9qdng3896akrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
